
package com.epam.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WalletService", targetNamespace = "http://soap.Web.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WalletService {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableAmount", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.GetAvailableAmount")
    @ResponseWrapper(localName = "getAvailableAmountResponse", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.GetAvailableAmountResponse")
    public double getAvailableAmount();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeWithdraw", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.MakeWithdraw")
    @ResponseWrapper(localName = "makeWithdrawResponse", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.MakeWithdrawResponse")
    public boolean makeWithdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeIncome", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.MakeIncome")
    @ResponseWrapper(localName = "makeIncomeResponse", targetNamespace = "http://soap.Web.epam.com/", className = "com.epam.soap.MakeIncomeResponse")
    public boolean makeIncome(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
