
package com.epam.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WalletServiceImpService", targetNamespace = "http://soap.Web.epam.com/", wsdlLocation = "http://localhost:8080/BogdanSprysaWalletService/walletSoap?wsdl")
public class WalletServiceImpService
    extends Service
{

    private final static URL WALLETSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WALLETSERVICEIMPSERVICE_EXCEPTION;
    private final static QName WALLETSERVICEIMPSERVICE_QNAME = new QName("http://soap.Web.epam.com/", "WalletServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BogdanSprysaWalletService/walletSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WALLETSERVICEIMPSERVICE_WSDL_LOCATION = url;
        WALLETSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public WalletServiceImpService() {
        super(__getWsdlLocation(), WALLETSERVICEIMPSERVICE_QNAME);
    }

    public WalletServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WALLETSERVICEIMPSERVICE_QNAME, features);
    }

    public WalletServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, WALLETSERVICEIMPSERVICE_QNAME);
    }

    public WalletServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WALLETSERVICEIMPSERVICE_QNAME, features);
    }

    public WalletServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WalletServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WalletService
     */
    @WebEndpoint(name = "WalletServiceImpPort")
    public WalletService getWalletServiceImpPort() {
        return super.getPort(new QName("http://soap.Web.epam.com/", "WalletServiceImpPort"), WalletService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WalletService
     */
    @WebEndpoint(name = "WalletServiceImpPort")
    public WalletService getWalletServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.Web.epam.com/", "WalletServiceImpPort"), WalletService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WALLETSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw WALLETSERVICEIMPSERVICE_EXCEPTION;
        }
        return WALLETSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
